Introduce a 'Create New Hyphae' special url and top bar highlight
bouncepaw/mycorrhiza pull request #123
Opened 2021-12-29 01:08 UTC by roselandgoose

- Adds a /new handler which simply redirects to a queried page.
- Prevents redirect on empty input by sending NO CONTENT
- Recognizes special case header link /new and creates input bar.

2021-12-29 06:57 UTC, handlerug requested changes
Thanks for the contribution! Left some nitpicks during the review, but otherwise looks very good to me. Here's how it looks in Chrome:
![image](https://user-images.githubusercontent.com/24986597/147634956-d13a888d-637a-4678-a80e-fdbbf9397f6d.png)

And the same thing but if I add it to the end:
![image](https://user-images.githubusercontent.com/24986597/147635001-278fff32-a3d5-4089-8d1a-916d5261fc3a.png)

The "replacing /new links with an input field" idea seems clever to me! Not sure if it fits well in the top bar, though; it looks messy, especially with those dark heavy outlines (you _could_ blame Chrome for that, but there were styles that removed it before). Maybe @bouncepaw can think of a better placement for it? He also had an idea of a big "New" button for creating hyphae, and I had an idea of an ultimate JavaScript-enhanced field with existing hyphae autocompletion and fast editing shortcuts.

I'd also love some way of creating new hyphae relative to the one the user is currently at. So, if the user is currently browsing Fruits/Apple and they want to add a subhypha, they can type in "./Nutrients" and have Fruits/Apple/Nutrients hypha opened for editing. You just need to resolve the new path relative to the URL the user is coming from (`Referer` HTTP header), like it's done for links in Mycomarkup.

2021-12-29 06:57 UTC, handlerug commented on static/default.css
> +    display: block;
Nitpick: indentation

2021-12-29 06:57 UTC, handlerug commented on web/stuff.go
> +		new_path := rq.URL.Query().Get("new-path")
Nitpick: prefer camelCase for variable names

2022-01-02 18:48 UTC, bouncepaw reviewed
Although I like the whole idea of having a way to create _a_ hypha, this pull request does not solve the problem.

The proposed input line in the top bar plays the role of a stripped-down address bar in the browser. @handlerug had an idea of relative names in that input; it is already supported by the address bar.

What would work is a link to a page where you create a hypha. A link, not an input, to not force users to think of the name beforehand.

2022-01-02 18:48 UTC, bouncepaw commented on views/stuff.qtpl
> +									<input class="top-bar__highlight-new-input" size="{%s inputSize(link.Display) %}" type="text" name="new-path" placeholder="{%s link.Display %}">
Few things.

* A second input line in the top bar is not a good idea.
* This input offers nothing more than the address bar in any browser.

2022-01-02 18:50 UTC, bouncepaw commented
I'm closing this pull request for now because it does not solve the problem and offers nothing new.

Nonetheless, we sure need something like that! I will open an issue regarding that. Thanks for bringing the attention to the topic.

2022-01-02 18:50 UTC, closed without merging