Add default favicon.ico file
bouncepaw/mycorrhiza pull request #162
Opened 2022-08-21 02:27 UTC by opsyne

![mushroom](https://raw.githubusercontent.com/twitter/twemoji/54df6a1340154c4f5bad09c85de8b720c5373c03/assets/72x72/1f344.png)

I thought this would be a fitting default favicon. It's taken from twitter's twemoji. It's licensed under CC BY 4.0, but the twemoji project has more lax guidelines for attribution:

> However, we consider the guide a bit onerous and as a project, will accept a mention in a project README or an 'About' section or footer on a website.

2022-08-21 08:45 UTC, bouncepaw requested changes
Checked the favicon on dark and light theme on laptop and smartphone, looks great.

What if somebody wants to _not_ have a favicon? What do they do?

2022-08-21 08:45 UTC, bouncepaw commented on README.md
> +The `static/favico.ico` file in this repository is the [mushroom emoji](https://github.com/twitter/twemoji/blob/54df6a1/assets/72x72/1f344.png) from Twitter's [twemoji project](https://twemoji.twitte
favicon -> favicon

And the point it missing at the end of the sentence.

2022-08-21 17:12 UTC, opsyne commented
> What if somebody wants to not have a favicon? What do they do?

Hmm, that's a good point. We could add a config option called `UseDefaultFavicon`, but that might complicate the route handling a little bit. Telling users to create a transparent 1x1 px png could also work, but I feel like that's a pretty bad solution from a UX standpoint.

I'm a fan of the config option, personally. But if anyone else has a better idea I'm all for it!

2022-08-21 17:15 UTC, handlerug commented
How about bundling the favicon with Mycorrhiza then extracting it into `<wiki_path>/static/` on wiki creation? This way, people who don't want this icon can delete it. And we don't have to pollute the config file as well.

2022-08-21 18:36 UTC, bouncepaw commented
> We could add a config option called `UseDefaultFavicon`

I avoid options generally. What happens if `UseDefaultFavicon=true`, but there is a `wiki/static/favicon.ico` provided by user?

> Telling users to create a transparent 1x1 px png could also work, but I feel like that's a pretty bad solution from a UX standpoint.

It is.

> How about bundling the favicon with Mycorrhiza then extracting it into `<wiki_path>/static/` on wiki creation?

That might work. Mycorrhiza creates a lot of files anyway.


----

Regarding the licensing of the icon. I just remembered we already have icons from other projects. Their sources are mentioned on `static/icon/README.md`, it makes more sense to have the licensing info for the shroom there as well.

2022-08-21 18:55 UTC, opsyne commented
> How about bundling the favicon with Mycorrhiza then extracting it into <wiki_path>/static/ on wiki creation?

+1 from me as well

> Regarding the licensing of the icon. I just remembered we already have icons from other projects. Their sources are mentioned on static/icon/README.md, it makes more sense to have the licensing info for the shroom there as well.

Sounds good!

2022-08-22 07:10 UTC, opsyne commented
Like I mentioned in the commit message, that solution might be a bit over-engineered.

2022-08-22 07:56 UTC, handlerug commented
Looks completely fine to me! My only concern (just noticed) is that the icon is a PNG file, but the name is `favicon.ico` as if it's an ICO image file. That shouldn't be an issue (every mainstream browser will double-check the magic bytes anyway), but maybe @bouncepaw has a different opinion. (By the way, ICO files support embedding PNG-compressed images.)

2022-08-22 07:58 UTC, handlerug commented on files/files.go
> +			return err
Though you may want to just log the error without taking down the program because those assets aren't critical at all.

2022-08-22 08:26 UTC, bouncepaw commented
PNG is fine.

2022-08-22 08:29 UTC, bouncepaw approved these changes

2022-08-22 08:31 UTC, merged